
# NOTE: written by carbon shell
[colors]
[colors.primary]
foreground = "#e9eef1"
background = "#0f1416"

[colors.normal]
red     = "#ce6f79"
yellow  = "#ceec76"
green   = "#4eec76"
cyan    = "#58ecf6"
blue    = "#5085f6"
magenta = "#ce70f6"
white   = "#ceecf6"
black   = "#35535d"

[colors.bright]
red     = "#ce6f79"
yellow  = "#ceec76"
green   = "#4eec76"
cyan    = "#58ecf6"
blue    = "#5085f6"
magenta = "#ce70f6"
white   = "#ceecf6"
black   = "#35535d"
