// NOTE: written by carbon shell
selection_foreground     #e9eef1
selection_background     #343a3c
active_border_color      #e9eef1
inactive_border_color    #e9eef1
active_tab_foreground    #e9eef1
active_tab_background    #1f2527
inactive_tab_foreground  #e9eef1
inactive_tab_background  #0f1416
background               #0f1416
foreground               #e9eef1
color0                   #35535d
color1                   #ce6f79
color2                   #4eec76
color3                   #ceec76
color4                   #5085f6
color5                   #ce70f6
color6                   #58ecf6
color7                   #ceecf6
color8                   #35535d
color9                   #ce6f79
color10                  #4eec76
color11                  #ceec76
color12                  #5085f6
color13                  #ce70f6
color14                  #58ecf6
color15                  #ceecf6
cursor                   #e9eef1
cursor_text_color        #e9eef1
url_color                #c1c4eb
