[hypr_override]
src  = "hypr/override.conf"
dest = "~/.config/hypr/override.conf"

[kitty]
src  = "kitty"
dest = "~/.config/kitty"

[zshrc]
src  = "zsh/.zshrc"
dest = "~/.zshrc"

[zshenv]
src  = "zsh/.zshenv"
dest = "~/.zshenv"

[zsh_autocomplete]
src  = "zsh/.zshac"
dest = "~/.zshac"

[alacritty]
src  = "alacritty"
dest = "~/.config/alacritty"

[fastfetch]
src  = "fastfetch"
dest = "~/.config/fastfetch"

[starship]
src  = "starship/starship.toml"
dest = "~/.config/starship.toml"
