

general {

	border_size = 0

    gaps_in = 6
    gaps_out = 10

    col.active_border = $border_active
    col.inactive_border = $border_inactive

    resize_on_border = true

    allow_tearing = false

    layout = dwindle

	snap {
		enabled = true
	}
}

decoration {
    rounding = 12
    rounding_power = 3.0

    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    dim_modal = true
    dim_inactive = true
    dim_strength = 0.12

	blur {
		enabled = true
		size = 5
		passes = 2
		noise = 0.002
		vibrancy = 10
		popups = true
	}

	shadow {
		enabled = true
		color = rgba(111111aa)
		range = 10
	}
}


misc {
	font_family = Ioesvka
}

