# NOTE: written by carbon shell
$border_active = rgb(40484b)
$border_inactive = rgba(40484b40)
$background = rgb(0f1416)
$surface = rgb(0f1416)
$onSurface = rgb(e9eef1)
$primary = rgb(86d1ea)
$onPrimary = rgb(002833)
$primaryContainer = rgb(21768c)
$error = rgb(ffb4ab)
$errorContainer = rgb(cf2c27)
$onErrorContainer = rgb(ffffff)
